### ISSUE TITLE
panic: cant find keyval map

### ISSUE THREAD

**Issue by damemi** [open-telemetry/opentelemetry-go-instrumentation#17]
### Describe the bug

Running `otel-go-instrumentation` on a simple binary produces the following failure:
```
{"level":"info","ts":1668622016.422307,"caller":"cli/main.go:37","msg":"starting Go OpenTelemetry Agent ..."}
{"level":"info","ts":1668622016.422393,"caller":"opentelemetry/controller.go:107","msg":"Establishing connection to OpenTelemetry collector ..."}
{"level":"info","ts":1668622018.4382257,"caller":"process/discover.go:57","msg":"found process","pid":157218}
panic: cant find keyval map

goroutine 1 [running]:
github.com/open-telemetry/opentelemetry-go-instrumentation/pkg/process.(*processAnalyzer).findKeyvalMmap(0xb48c60?, 0xc0001328c0?)
	/usr/local/google/home/mikedame/go/src/github.com/open-telemetry/opentelemetry-go-instrumentation/pkg/process/analyze.go:92 +0x14f
github.com/open-telemetry/opentelemetry-go-instrumentation/pkg/process.(*processAnalyzer).Analyze(0xc000482120?, 0x26622, 0x2?)
	/usr/local/google/home/mikedame/go/src/github.com/open-telemetry/opentelemetry-go-instrumentation/pkg/process/analyze.go:118 +0x1a9
main.main()
	/usr/local/google/home/mikedame/go/src/github.com/open-telemetry/opentelemetry-go-instrumentation/cli/main.go:74 +0x37f
```

### Environment

- sample app built with go 1.18 (using `golang:1.18` docker container)

### To Reproduce

I am building the following code ([from here](https://gowebexamples.com/routes-using-gorilla-mux/):
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gorilla/mux"
)

func main() {
	r := mux.NewRouter()

	r.HandleFunc("/books/{title}/page/{page}", func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		title := vars["title"]
		page := vars["page"]

		fmt.Fprintf(w, "You've requested the book: %s on page %s\n", title, page)
	})

	log.Fatal(http.ListenAndServe(":8080", r))
}
```

Save, run `go mod init` and `go tidy` then build with `go build -o gm main.go`.

Run with `./gm &`

Start a local OTEL collector at `localhost:4317`

Build the auto-instrumentation tool with `make build`

Run auto-instrumentation with the following command:
```
OTEL_SERVICE_NAME=otel-collector \
OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 \
OTEL_TARGET_EXE=/path/to/gm ./otel-go-instrumentation
```

### Expected behavior

Auto-instrumentation to work, or provide clearer information about what went wrong and how I can fix it.

### Additional context

I'm still figuring out ebpf, but from the code the error comes from https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/e42d188a44e6d5fc26607ac92689285a0802fb51/pkg/process/analyze.go#L92. I got enough from there to check `/proc/<id>/maps` and it looks like none of the maps have the full read/write/execute permissions that auto-instrumentation needs:

```
$ cat /proc/157218/maps
00400000-00623000 r-xp 00000000 fe:00 8129336                            /path/to/gm
00623000-00823000 r--p 00223000 fe:00 8129336                            /path/to/gm
00823000-00861000 rw-p 00423000 fe:00 8129336                            /path/to/gm
00861000-0089a000 rw-p 00000000 00:00 0 
01b66000-01b87000 rw-p 00000000 00:00 0                                  [heap]
c000000000-c000400000 rw-p 00000000 00:00 0 
c000400000-c004000000 ---p 00000000 00:00 0 
7fe4ac000000-7fe4ac021000 rw-p 00000000 00:00 0 
7fe4ac021000-7fe4b0000000 ---p 00000000 00:00 0 
7fe4b0000000-7fe4b0021000 rw-p 00000000 00:00 0 
7fe4b0021000-7fe4b4000000 ---p 00000000 00:00 0 
7fe4b4000000-7fe4b4021000 rw-p 00000000 00:00 0 
7fe4b4021000-7fe4b8000000 ---p 00000000 00:00 0 
7fe4b8000000-7fe4b8021000 rw-p 00000000 00:00 0 
7fe4b8021000-7fe4bc000000 ---p 00000000 00:00 0 
7fe4bc000000-7fe4bc021000 rw-p 00000000 00:00 0 
7fe4bc021000-7fe4c0000000 ---p 00000000 00:00 0 
7fe4c02ea000-7fe4c02eb000 ---p 00000000 00:00 0 
7fe4c02eb000-7fe4c0aeb000 rw-p 00000000 00:00 0 
7fe4c0aeb000-7fe4c0aec000 ---p 00000000 00:00 0 
7fe4c0aec000-7fe4c12ec000 rw-p 00000000 00:00 0 
7fe4c12ec000-7fe4c12ed000 ---p 00000000 00:00 0 
7fe4c12ed000-7fe4c1aed000 rw-p 00000000 00:00 0 
7fe4c1aed000-7fe4c1aee000 ---p 00000000 00:00 0 
7fe4c1aee000-7fe4c22ee000 rw-p 00000000 00:00 0 
7fe4c22ee000-7fe4c22ef000 ---p 00000000 00:00 0 
7fe4c22ef000-7fe4c4e00000 rw-p 00000000 00:00 0 
7fe4c4e00000-7fe4d4f80000 ---p 00000000 00:00 0 
7fe4d4f80000-7fe4d4f81000 rw-p 00000000 00:00 0 
7fe4d4f81000-7fe4e6e30000 ---p 00000000 00:00 0 
7fe4e6e30000-7fe4e6e31000 rw-p 00000000 00:00 0 
7fe4e6e31000-7fe4e9206000 ---p 00000000 00:00 0 
7fe4e9206000-7fe4e9207000 rw-p 00000000 00:00 0 
7fe4e9207000-7fe4e9600000 ---p 00000000 00:00 0 
7fe4e9600000-7fe4e9628000 r--p 00000000 fe:00 2359372                    /usr/lib/x86_64-linux-gnu/libc.so.6
7fe4e9628000-7fe4e9798000 r-xp 00028000 fe:00 2359372                    /usr/lib/x86_64-linux-gnu/libc.so.6
7fe4e9798000-7fe4e97f0000 r--p 00198000 fe:00 2359372                    /usr/lib/x86_64-linux-gnu/libc.so.6
7fe4e97f0000-7fe4e97f4000 r--p 001f0000 fe:00 2359372                    /usr/lib/x86_64-linux-gnu/libc.so.6
7fe4e97f4000-7fe4e97f6000 rw-p 001f4000 fe:00 2359372                    /usr/lib/x86_64-linux-gnu/libc.so.6
7fe4e97f6000-7fe4e9803000 rw-p 00000000 00:00 0 
7fe4e9810000-7fe4e9860000 rw-p 00000000 00:00 0 
7fe4e9860000-7fe4e98e0000 ---p 00000000 00:00 0 
7fe4e98e0000-7fe4e98e1000 rw-p 00000000 00:00 0 
7fe4e98e1000-7fe4e9960000 ---p 00000000 00:00 0 
7fe4e9960000-7fe4e99c3000 rw-p 00000000 00:00 0 
7fe4e99c3000-7fe4e99c4000 r--p 00000000 fe:00 2366791                    /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fe4e99c4000-7fe4e99c5000 r-xp 00001000 fe:00 2366791                    /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fe4e99c5000-7fe4e99c6000 r--p 00002000 fe:00 2366791                    /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fe4e99c6000-7fe4e99c7000 r--p 00002000 fe:00 2366791                    /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fe4e99c7000-7fe4e99c8000 rw-p 00003000 fe:00 2366791                    /usr/lib/x86_64-linux-gnu/libpthread.so.0
7fe4e99cf000-7fe4e99e1000 rw-p 00000000 00:00 0 
7fe4e99e1000-7fe4e99e3000 r--p 00000000 fe:00 2359341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fe4e99e3000-7fe4e9a09000 r-xp 00002000 fe:00 2359341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fe4e9a09000-7fe4e9a14000 r--p 00028000 fe:00 2359341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fe4e9a14000-7fe4e9a16000 r--p 00033000 fe:00 2359341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fe4e9a16000-7fe4e9a18000 rw-p 00035000 fe:00 2359341                    /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
7fff80864000-7fff80886000 rw-p 00000000 00:00 0                          [stack]
7fff809be000-7fff809c2000 r--p 00000000 00:00 0                          [vvar]
7fff809c2000-7fff809c4000 r-xp 00000000 00:00 0                          [vdso]
```

Not sure what to do with this or how to fix it

**Comment by damemi** [comment]
ping @edeNFed I realize this is probably not a bug, but something I'm doing wrong. do you know what this issue could be?

**Comment by edeNFed** [comment]
I'll try to explain why we need this map and how it is created.
* Trace ids and span ids are generated in eBPF (if not propagated from the incoming request). In order to add the generated values to the request headers we need to be able to read them from within the Go application, which obviously can't access memory in kernel space. The way we solve this is by allocating off-heap memory on the Go application (1Mb if I am not mistaken) which the eBPF program writes into. This allocation happens only once - when the application starts. 

* You can create this memory area in two ways: A. via code - invoke the `mmap` syscall and the instrumentation agent will find it. B. via launcher - a small program that I wrote that allocates this map area and then starts the target application. Unfortunately, I didn't have time to release it as open source yet (hopefully will happen next week). For now, you can use the docker image `keyval/launcher:v0.1` and use it like [here](https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/main/docs/getting-started/emojivoto-instrumented.yaml)

Hope that makes sense, please let me know if it's still not clear.

**Comment by damemi** [comment]
Thanks @edeNFed, that's very helpful! So is it correct that right now, this auto-instrumentation requires either code changes (invoking `mmap`) or to use your launcher to work?

It would be great if you could contribute the code/dockerfile for the launcher to this repo, so we can package something users can run out of the box.

**Comment by edeNFed** [comment]
Sure, will open a PR shortly

**Comment by dineshg13** [comment]
@edeNFed as suggested on slack, i started to use https://github.com/keyval-dev/launcher , to launch the binary . Am now getting a new error 

```
{"level":"info","ts":1670773134.3289542,"caller":"cli/main.go:37","msg":"starting Go OpenTelemetry Agent ..."}
{"level":"info","ts":1670773134.3289938,"caller":"opentelemetry/controller.go:107","msg":"Establishing connection to OpenTelemetry collector ..."}
{"level":"info","ts":1670773136.3361652,"caller":"process/discover.go:57","msg":"found process","pid":112920}
{"level":"info","ts":1670773136.3364372,"caller":"process/analyze.go:88","msg":"found addr of keyval map","addr":139924897234944}
{"level":"info","ts":1670773136.3405275,"caller":"process/analyze.go:151","msg":"found relevant function for instrumentation","function":"google.golang.org/grpc/internal/transport.(*http2Client).createHeaderFields","returns":3}
{"level":"info","ts":1670773136.340637,"caller":"process/analyze.go:151","msg":"found relevant function for instrumentation","function":"google.golang.org/grpc.(*ClientConn).Invoke","returns":2}
{"level":"info","ts":1670773136.3408015,"caller":"process/analyze.go:151","msg":"found relevant function for instrumentation","function":"google.golang.org/grpc.(*Server).handleStream","returns":5}
{"level":"info","ts":1670773136.340816,"caller":"cli/main.go:79","msg":"target process analysis completed","pid":112920,"go_version":"1.19.1","dependencies":{"github.com/golang/protobuf":"v1.5.2","github/dineshg13/goplay/libs/logging":"v0.0.0-00010101000000-000000000000","github/dineshg13/goplay/protos":"v0.0.0-00010101000000-000000000000","go.uber.org/atomic":"v1.7.0","go.uber.org/multierr":"v1.6.0","go.uber.org/zap":"v1.24.0","golang.org/x/net":"v0.0.0-20220722155237-a158d28d115b","golang.org/x/sys":"v0.0.0-20220722155257-8c9f86f7a55f","golang.org/x/text":"v0.4.0","google.golang.org/genproto":"v0.0.0-20200526211855-cb27e3aa2013","google.golang.org/grpc":"v1.49.0","google.golang.org/protobuf":"v1.28.1"},"total_functions_found":3}
{"level":"info","ts":1670773136.341011,"caller":"cli/main.go:85","msg":"invoking instrumentors"}
{"level":"info","ts":1670773136.3461616,"logger":"allocator","caller":"allocator/allocator_linux.go:34","msg":"Loading allocator","start_addr":139924897234944,"end_addr":139924897247232}
{"level":"info","ts":1670773136.3470068,"caller":"instrumentors/runner.go:83","msg":"loading instrumentor","name":"google.golang.org/grpc"}
{"level":"info","ts":1670773136.3480148,"caller":"inject/injector.go:82","msg":"Injecting variables","vars":{"clientconn_target_ptr_pos":24,"end_addr":139924897247232,"is_registers_abi":true,"start_addr":139924897234944,"total_cpus":32}}
{"level":"error","ts":1670773136.3515298,"caller":"instrumentors/runner.go:86","msg":"error while loading instrumentors, cleaning up","name":"google.golang.org/grpc","error":"field UprobeHttp2ClientCreateHeaderFields: program uprobe_Http2Client_CreateHeaderFields: load program: permission denied: R1 type=ctx expected=fp\n0: R1=ctx(off=0,imm=0) R10=fp0\n; int uprobe_Http2Client_CreateHeaderFields(struct pt_regs *ctx)\n0: (bf) r6 = r1                       ; R1=ctx(off=0,imm=0) R6_w=ctx(off=0,imm=0)\n1: (b7) r1 = 0                        ; R1_w=0\n; struct go_slice slice = {};\n2: (7b) *(u64 *)(r10 -96) = r1        ; R1_w=P0 R10=fp0 fp-96_w=00000000\n3: (7b) *(u64 *)(r10 -104) = r1       ; R1_w=P0 R10=fp0 fp-104_w=00000000\n; if (is_registers_abi)\n4: (18) r1 = 0xffff9c5890049510       ; R1_w=map_value(off=0,ks=4,vs=48,imm=0)\n6: (71) r2 = *(u8 *)(r1 +0)           ; R1_w=map_value(off=0,ks=4,vs=48,imm=0) R2_w=scalar(umax=255,var_off=(0x0; 0xff))\n; if (is_registers_abi)\n7: (7b) *(u64 *)(r10 -448) = r6       ; R6_w=ctx(off=0,imm=0) R10=fp0 fp-448_w=ctx\n8: (15) if r2 == 0x0 goto pc+15       ; R2_w=scalar(umax=255,var_off=(0x0; 0xff))\n; slice.array = (void *)ctx->rax;\n9: (79) r1 = *(u64 *)(r6 +80)         ; R1_w=scalar() R6_w=ctx(off=0,imm=0)\n; slice.array = (void *)ctx->rax;\n10: (7b) *(u64 *)(r10 -104) = r1      ; R1_w=scalar() R10=fp0 fp-104_w=mmmmmmmm\n; slice.len = (s32)ctx->rbx;\n11: (7```

**Comment by edeNFed** [comment]
@dineshg13 Can you please give more details about the kernel version that you are using? it will help me to try to reproduce it (output of running `uname -r` will be great)

**Comment by damemi** [comment]
@edeNFed just checking, were you planning to donate the launcher code as well? I think that's the final piece of this

**Comment by edeNFed** [comment]
@damemi I found a way to allocate memory without the launcher, will open a PR that includes the new mechanism soon.

**Comment by mariomac** [comment]
This PR should help if you are not instrumenting GRPC services: https://github.com/open-telemetry/opentelemetry-go-instrumentation/pull/32
