### ISSUE TITLE
Panic: send on closed channel

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-instrumentation#976]
### Describe the bug

When terminating the auto-instrumentation CLI using `^C` the following panic occurs:

```terminal
^Cpanic: send on closed channel

goroutine 43 [running]:
go.opentelemetry.io/auto/internal/pkg/instrumentation/probe.(*Base[...]).Run(0xe2b700, 0xc0000220c0)
	/home/tyler/go/src/go.opentelemetry.io/auto/internal/pkg/instrumentation/probe/probe.go:211 +0x2d1
go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).Run.func1({0xe23790?, 0xc0003ca500?})
	/home/tyler/go/src/go.opentelemetry.io/auto/internal/pkg/instrumentation/manager.go:153 +0x64
created by go.opentelemetry.io/auto/internal/pkg/instrumentation.(*Manager).Run in goroutine 1
	/home/tyler/go/src/go.opentelemetry.io/auto/internal/pkg/instrumentation/manager.go:151 +0x18a
```

### Environment

 - OS: Linux xi 6.10.2-arch1-1
 - Go Version: 1.22.5
 - Version: dfd43b3

### To Reproduce

1. Run the `user` service from https://github.com/MrAlias/otel-auto-demo using `go build -o $GOPATH/bin/user ./... && $GOPATH/bin/user`
2. Run the auto-instrumentation cli: `OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 OTEL_GO_AUTO_TARGET_EXE=$GOPATH/bin/user OTEL_SERVICE_NAME=user OTEL_GO_AUTO_GLOBAL=true sudo -E ./cli`
3. Exit the CLI with `<CTRL>C`

### Expected behavior

No panic and a clean shutdown

**Comment by MrAlias** [comment]
This dirty shutdown fails to remove the associated BPF files. On a subsequent start-up:

```terminal
{"level":"error","ts":1722362721.8885372,"logger":"go.opentelemetry.io/auto","caller":"cli/main.go:121","msg":"instrumentation crashed","error":"mkdir /sys/fs/bpf/65680: file exists","stacktrace":"main.main\n\t/home/tyler/go/src/go.opentelemetry.io/auto/cli/main.go:121\nruntime.main\n\t/usr/lib/go/src/runtime/proc.go:271"}
```

**Comment by MrAlias** [comment]
`m.incomingEvents` is being closed ...

https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/f8dc5ab3e12caa26501fe905a388befcc0c8615d/internal/pkg/instrumentation/manager.go#L220

before all probes are closed and verified to be stopped:

https://github.com/open-telemetry/opentelemetry-go-instrumentation/blob/f8dc5ab3e12caa26501fe905a388befcc0c8615d/internal/pkg/instrumentation/manager.go#L221-L223
